server:
  port: 8080
  servlet:
    context-path: "/api"

api:
  data:
    scheme: "http"
    host: "localhost"
    port: "8081"
    url: "/data/people"

logging:
  level:
    ru.smaginv.api: debug
    org.springframework.web.servlet: debug
  charset:
    console: UTF-8
  pattern:
    console: "%d{HH:mm:ss} %clr(%5p) %-65.65(%clr(%logger{50}){cyan}) : %msg%n"
